name: Nivashini new Workflow

 
on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Build application
        run: echo "Building application"
 
  smoke_tests:
    name: Smoke Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
 
      - name: Run smoke tests
        run: pytest tests/smoke/ --junitxml=smoke-results.xml
 
      - name: Upload smoke test results
        uses: actions/upload-artifact@v4
        with:
          name: smoke-results
          path: smoke-results.xml
 
  regression_tests:
    name: Regression Tests
    runs-on: ubuntu-latest
    needs: smoke_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
 
      - name: Run regression tests
        run: pytest tests/regression/ --junitxml=regression-results.xml
 
      - name: Upload regression results
        uses: actions/upload-artifact@v4
        with:
          name: regression-results
          path: regression-results.xml
 
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: regression_tests
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Deploy application
        run: ./deploy.sh
 
